name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  installandtest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        # Run on the latest minor release of Go 1.21:
        go-version: ^1.21
      id: go

    - name: Ensure all files were formatted as per gofmt
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: install binaries
      run: go install ./cmd/... ./ github.com/robustirc/bridge/robustirc-bridge

    - name: run tests
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go test ./...

